# Generated by Django 4.2.26 on 2025-11-06 05:24

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 7), ('service_cards', 16), ('image_text', 18), ('contact_form', 21)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Main heading', 'max_length': 255, 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Subheading text', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Call to action button text', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Call to action link', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Secondary button text', 'max_length': 100, 'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'help_text': 'Secondary button link', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subheading', 1), ('background_image', 2), ('cta_text', 3), ('cta_link', 4), ('secondary_cta_text', 5), ('secondary_cta_link', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 9: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 11: ('wagtail.blocks.TextBlock', (), {'max_length': 300, 'required': False}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': "Icon class name (e.g., 'fa-certificate')", 'max_length': 50, 'required': False}), 13: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 14: ('wagtail.blocks.StructBlock', [[('title', 10), ('description', 11), ('icon', 12), ('link', 13)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {}), 16: ('wagtail.blocks.StructBlock', [[('heading', 8), ('subheading', 9), ('cards', 15)]], {}), 17: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('right', 'Right')]}), 18: ('wagtail.blocks.StructBlock', [[('image', 2), ('heading', 8), ('text', 9), ('image_position', 17)]], {}), 19: ('wagtail.blocks.TextBlock', (), {'required': False}), 20: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('light-blue', 'Light Blue'), ('dark-blue', 'Dark Blue'), ('white', 'White')]}), 21: ('wagtail.blocks.StructBlock', [[('heading', 8), ('subheading', 19), ('background_color', 20)]], {})}),
        ),
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_search', models.BooleanField(default=True, help_text='Show search bar in navigation')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Navigation Settings',
            },
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('copyright_text', models.CharField(blank=True, default='© 2025 All rights reserved', max_length=255)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Footer Settings',
            },
        ),
    ]
