# Generated by Django 4.2.26 on 2025-11-06 07:17

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('home', '0004_alter_homepage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Menu title (for admin reference only)', max_length=100)),
            ],
            options={
                'verbose_name': 'Main Menu',
                'verbose_name_plural': 'Main Menus',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(help_text='Menu item title', max_length=100)),
                ('link_url', models.URLField(blank=True, help_text='Or link to an external URL')),
                ('open_in_new_tab', models.BooleanField(default=False, help_text='Open link in new tab')),
                ('icon_class', models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fa-home')", max_length=100)),
                ('link_page', models.ForeignKey(blank=True, help_text='Link to a page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('menu', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='home.mainmenu')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
            },
        ),
        migrations.CreateModel(
            name='SubMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(help_text='Submenu item title', max_length=100)),
                ('link_url', models.URLField(blank=True, help_text='Or link to an external URL')),
                ('open_in_new_tab', models.BooleanField(default=False, help_text='Open link in new tab')),
                ('icon_class', models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fa-home')", max_length=100)),
                ('description', models.CharField(blank=True, help_text='Optional description for the menu item', max_length=200)),
                ('link_page', models.ForeignKey(blank=True, help_text='Link to a page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('parent', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenu_items', to='home.menuitem')),
            ],
            options={
                'verbose_name': 'Submenu Item',
                'verbose_name_plural': 'Submenu Items',
            },
        ),
        migrations.CreateModel(
            name='SiteMenuSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_menu', models.ForeignKey(blank=True, help_text='Select the menu to display in the navigation bar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.mainmenu')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Site Menu Settings',
            },
        ),
    ]
