# Generated by Django 4.2.26 on 2025-11-06 07:28

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('home', '0005_mainmenu_menuitem_submenuitem_sitemenusettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(help_text='Column heading', max_length=100)),
            ],
            options={
                'verbose_name': 'Footer Column',
                'verbose_name_plural': 'Footer Columns',
            },
        ),
        migrations.CreateModel(
            name='FooterMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Footer menu title (for admin reference only)', max_length=100)),
            ],
            options={
                'verbose_name': 'Footer Menu',
                'verbose_name_plural': 'Footer Menus',
            },
        ),
        migrations.AddField(
            model_name='footersettings',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='show_contact_info',
            field=models.BooleanField(default=True, help_text='Show contact information in footer'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(help_text='Link text', max_length=100)),
                ('link_url', models.URLField(blank=True, help_text='Or link to an external URL')),
                ('open_in_new_tab', models.BooleanField(default=False, help_text='Open link in new tab')),
                ('column', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_links', to='home.footercolumn')),
                ('link_page', models.ForeignKey(blank=True, help_text='Link to a page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Footer Link',
                'verbose_name_plural': 'Footer Links',
            },
        ),
        migrations.AddField(
            model_name='footercolumn',
            name='footer_menu',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_columns', to='home.footermenu'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='footer_menu',
            field=models.ForeignKey(blank=True, help_text='Select the footer menu to display', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.footermenu'),
        ),
    ]
