# Generated by Django 4.2.26 on 2025-11-06 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('home', '0007_alter_homepage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#0066cc', help_text='Main brand color (e.g., #0066cc)', max_length=7)),
                ('secondary_color', models.CharField(default='#28a745', help_text='Secondary brand color (e.g., #28a745)', max_length=7)),
                ('accent_color', models.CharField(default='#ff6b6b', help_text='Accent/highlight color (e.g., #ff6b6b)', max_length=7)),
                ('navbar_background', models.CharField(default='#ffffff', help_text='Navbar background color', max_length=7)),
                ('navbar_text_color', models.CharField(default='#333333', help_text='Navbar text color', max_length=7)),
                ('navbar_hover_color', models.CharField(default='#0066cc', help_text='Navbar link hover color', max_length=7)),
                ('navbar_active_color', models.CharField(default='#0066cc', help_text='Active navbar link color', max_length=7)),
                ('footer_background', models.CharField(default='#2c3e50', help_text='Footer background color', max_length=7)),
                ('footer_text_color', models.CharField(default='#ecf0f1', help_text='Footer text color', max_length=7)),
                ('footer_link_color', models.CharField(default='#ffffff', help_text='Footer link color', max_length=7)),
                ('footer_link_hover_color', models.CharField(default='#3498db', help_text='Footer link hover color', max_length=7)),
                ('button_primary_bg', models.CharField(default='#0066cc', help_text='Primary button background', max_length=7)),
                ('button_primary_text', models.CharField(default='#ffffff', help_text='Primary button text color', max_length=7)),
                ('button_primary_hover', models.CharField(default='#0052a3', help_text='Primary button hover color', max_length=7)),
                ('button_secondary_bg', models.CharField(default='#6c757d', help_text='Secondary button background', max_length=7)),
                ('button_secondary_text', models.CharField(default='#ffffff', help_text='Secondary button text color', max_length=7)),
                ('button_secondary_hover', models.CharField(default='#5a6268', help_text='Secondary button hover color', max_length=7)),
                ('link_color', models.CharField(default='#0066cc', help_text='Default link color', max_length=7)),
                ('link_hover_color', models.CharField(default='#004999', help_text='Link hover color', max_length=7)),
                ('body_background', models.CharField(default='#f8f9fa', help_text='Body background color', max_length=7)),
                ('section_background', models.CharField(default='#ffffff', help_text='Section background color', max_length=7)),
                ('border_color', models.CharField(default='#dee2e6', help_text='Border and divider color', max_length=7)),
                ('heading_color', models.CharField(default='#212529', help_text='Heading text color', max_length=7)),
                ('body_text_color', models.CharField(default='#333333', help_text='Body text color', max_length=7)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Color Theme Settings',
            },
        ),
    ]
