# Generated by Django 4.2.26 on 2025-11-06 09:40

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('home', '0008_colorthemesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSubMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(help_text='Sub-submenu item title', max_length=100)),
                ('link_url', models.URLField(blank=True, help_text='Or link to an external URL')),
                ('open_in_new_tab', models.BooleanField(default=False, help_text='Open link in new tab')),
                ('icon_class', models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fa-home')", max_length=100)),
                ('description', models.CharField(blank=True, help_text='Optional description for the menu item', max_length=200)),
                ('link_page', models.ForeignKey(blank=True, help_text='Link to a page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('parent', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_submenu_items', to='home.submenuitem')),
            ],
            options={
                'verbose_name': 'Sub-submenu Item',
                'verbose_name_plural': 'Sub-submenu Items',
            },
        ),
    ]
