# Generated by Django 4.2.26 on 2025-11-14 11:14

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('home', '0009_subsubmenuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BottomNavMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Menu title (for admin reference only)', max_length=100)),
            ],
            options={
                'verbose_name': 'Bottom Navigation Menu',
                'verbose_name_plural': 'Bottom Navigation Menus',
            },
        ),
        migrations.CreateModel(
            name='BottomNavMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(help_text="ISO Standard (e.g., 'ISO 9001')", max_length=100)),
                ('link_url', models.URLField(blank=True, help_text='Or link to an external URL')),
                ('show_dropdown_arrow', models.BooleanField(default=False, help_text='Show dropdown arrow')),
                ('link_page', models.ForeignKey(blank=True, help_text='Link to a page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('menu', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_nav_items', to='home.bottomnavmenu')),
            ],
            options={
                'verbose_name': 'Bottom Nav Item',
                'verbose_name_plural': 'Bottom Nav Items',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='MiddleNavMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Menu title (for admin reference only)', max_length=100)),
                ('show_request_quote', models.BooleanField(default=True, help_text="Show 'Request a quote' button")),
                ('request_quote_text', models.CharField(default='Request a quote', help_text='Request quote button text', max_length=50)),
                ('request_quote_link', models.URLField(blank=True, help_text='Request quote button link')),
                ('show_client_portal', models.BooleanField(default=True, help_text="Show 'Client Portal' button")),
                ('client_portal_text', models.CharField(default='Client Portal', help_text='Client portal button text', max_length=50)),
                ('client_portal_link', models.URLField(blank=True, default='/admin/', help_text='Client portal button link')),
            ],
            options={
                'verbose_name': 'Middle Navigation Menu',
                'verbose_name_plural': 'Middle Navigation Menus',
            },
        ),
        migrations.CreateModel(
            name='TopNavMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Menu title (for admin reference only)', max_length=100)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number to display', max_length=20)),
                ('show_price', models.BooleanField(default=False, help_text='Show price badge (£0.00)')),
                ('price_text', models.CharField(blank=True, default='£0.00', help_text='Price text to display', max_length=20)),
            ],
            options={
                'verbose_name': 'Top Navigation Menu',
                'verbose_name_plural': 'Top Navigation Menus',
            },
        ),
        migrations.CreateModel(
            name='TopNavMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(help_text='Menu item title', max_length=100)),
                ('link_url', models.URLField(blank=True, help_text='Or link to an external URL')),
                ('open_in_new_tab', models.BooleanField(default=False, help_text='Open link in new tab')),
                ('icon_class', models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fa-home')", max_length=100)),
                ('show_dropdown_arrow', models.BooleanField(default=False, help_text='Show dropdown arrow icon')),
                ('link_page', models.ForeignKey(blank=True, help_text='Link to a page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('menu', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_nav_items', to='home.topnavmenu')),
            ],
            options={
                'verbose_name': 'Top Nav Item',
                'verbose_name_plural': 'Top Nav Items',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['sort_order'], 'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AlterModelOptions(
            name='submenuitem',
            options={'ordering': ['sort_order'], 'verbose_name': 'Submenu Item', 'verbose_name_plural': 'Submenu Items'},
        ),
        migrations.AlterModelOptions(
            name='subsubmenuitem',
            options={'ordering': ['sort_order'], 'verbose_name': 'Sub-submenu Item', 'verbose_name_plural': 'Sub-submenu Items'},
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('carousel', 15), ('hero', 23), ('heading', 27), ('paragraph', 30), ('html', 32), ('table', 33), ('embed_map', 37), ('image', 42), ('service_cards', 50), ('image_text', 52), ('quote', 56), ('button', 60), ('accordion', 64), ('columns', 67), ('spacer', 69), ('divider', 71), ('contact_form', 74)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('image', 'Image'), ('video', 'Video (YouTube/Vimeo)')], 'help_text': 'Choose between image or video slide'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Upload an image (for image slides)', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'YouTube or Vimeo URL (for video slides)', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Slide heading', 'max_length': 255, 'required': False}), 4: ('wagtail.blocks.TextBlock', (), {'help_text': 'Slide description', 'max_length': 500, 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Button text', 'max_length': 50, 'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'help_text': 'Button link', 'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right')], 'help_text': 'Position of text overlay'}), 8: ('wagtail.blocks.StructBlock', [[('slide_type', 0), ('image', 1), ('video_url', 2), ('heading', 3), ('description', 4), ('button_text', 5), ('button_link', 6), ('text_position', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'help_text': 'Add up to 6 slides', 'max_num': 6}), 10: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Auto-play carousel', 'required': False}), 11: ('wagtail.blocks.IntegerBlock', (), {'default': 5000, 'help_text': 'Auto-play speed in milliseconds (2000-10000)', 'max_value': 10000, 'min_value': 2000}), 12: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('fade', 'Fade'), ('slide', 'Slide'), ('zoom', 'Zoom')], 'help_text': 'Transition effect between slides'}), 13: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Show navigation dots', 'required': False}), 14: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Show navigation arrows', 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('slides', 9), ('autoplay', 10), ('autoplay_speed', 11), ('transition_effect', 12), ('show_dots', 13), ('show_arrows', 14)]], {}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': 'Main heading', 'max_length': 255, 'required': True}), 17: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Subheading text', 'required': False}), 18: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': 'Call to action button text', 'max_length': 100, 'required': False}), 20: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Call to action link', 'required': False}), 21: ('wagtail.blocks.CharBlock', (), {'help_text': 'Secondary button text', 'max_length': 100, 'required': False}), 22: ('wagtail.blocks.URLBlock', (), {'help_text': 'Secondary button link', 'required': False}), 23: ('wagtail.blocks.StructBlock', [[('heading', 16), ('subheading', 17), ('background_image', 18), ('cta_text', 19), ('cta_link', 20), ('secondary_cta_text', 21), ('secondary_cta_link', 22)]], {}), 24: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 25: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h1', 'Heading 1'), ('h2', 'Heading 2'), ('h3', 'Heading 3'), ('h4', 'Heading 4')]}), 26: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right')]}), 27: ('wagtail.blocks.StructBlock', [[('text', 24), ('level', 25), ('alignment', 26)]], {}), 28: ('wagtail.blocks.RichTextBlock', (), {}), 29: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right'), ('justify', 'Justify')]}), 30: ('wagtail.blocks.StructBlock', [[('content', 28), ('alignment', 29)]], {}), 31: ('wagtail.blocks.TextBlock', (), {'help_text': 'Enter HTML, CSS (wrapped in <style> tags), and JavaScript (wrapped in <script> tags)'}), 32: ('wagtail.blocks.StructBlock', [[('html', 31)]], {}), 33: ('wagtail.contrib.table_block.blocks.TableBlock', (), {}), 34: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Paste URL from YouTube, Vimeo, etc. (for oEmbed-compatible services)', 'required': False}), 35: ('wagtail.blocks.TextBlock', (), {'help_text': 'Or paste iframe embed code directly (for Google Maps, etc.)', 'required': False}), 36: ('wagtail.blocks.IntegerBlock', (), {'default': 450, 'help_text': 'Height in pixels', 'max_value': 1000, 'min_value': 200}), 37: ('wagtail.blocks.StructBlock', [[('embed_url', 34), ('iframe_code', 35), ('height', 36)]], {}), 38: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 39: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 40: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right'), ('full', 'Full Width')]}), 41: ('wagtail.blocks.URLBlock', (), {'help_text': 'Optional link URL', 'required': False}), 42: ('wagtail.blocks.StructBlock', [[('image', 38), ('caption', 39), ('alignment', 40), ('link', 41)]], {}), 43: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 44: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 45: ('wagtail.blocks.TextBlock', (), {'max_length': 300, 'required': False}), 46: ('wagtail.blocks.CharBlock', (), {'help_text': "Icon class name (e.g., 'fa-certificate')", 'max_length': 50, 'required': False}), 47: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 48: ('wagtail.blocks.StructBlock', [[('title', 44), ('description', 45), ('icon', 46), ('link', 47)]], {}), 49: ('wagtail.blocks.ListBlock', (48,), {}), 50: ('wagtail.blocks.StructBlock', [[('heading', 39), ('subheading', 43), ('cards', 49)]], {}), 51: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('right', 'Right')]}), 52: ('wagtail.blocks.StructBlock', [[('image', 18), ('heading', 39), ('text', 43), ('image_position', 51)]], {}), 53: ('wagtail.blocks.TextBlock', (), {}), 54: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 55: ('wagtail.blocks.CharBlock', (), {'help_text': 'Job title or company', 'max_length': 100, 'required': False}), 56: ('wagtail.blocks.StructBlock', [[('quote', 53), ('author', 54), ('author_title', 55), ('author_image', 18)]], {}), 57: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': True}), 58: ('wagtail.blocks.URLBlock', (), {'required': False}), 59: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary (Blue)'), ('secondary', 'Secondary (Outline)'), ('success', 'Success (Green)'), ('danger', 'Danger (Red)')]}), 60: ('wagtail.blocks.StructBlock', [[('text', 57), ('link_page', 47), ('link_url', 58), ('style', 59), ('alignment', 26)]], {}), 61: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 62: ('wagtail.blocks.StructBlock', [[('title', 61), ('content', 28)]], {}), 63: ('wagtail.blocks.ListBlock', (62,), {}), 64: ('wagtail.blocks.StructBlock', [[('items', 63)]], {}), 65: ('wagtail.blocks.StructBlock', [[('content', 28)]], {}), 66: ('wagtail.blocks.ListBlock', (65,), {'max_num': 4, 'min_num': 2}), 67: ('wagtail.blocks.StructBlock', [[('columns', 66)]], {}), 68: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('small', 'Small (30px)'), ('medium', 'Medium (60px)'), ('large', 'Large (100px)'), ('xlarge', 'Extra Large (150px)')]}), 69: ('wagtail.blocks.StructBlock', [[('height', 68)]], {}), 70: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('solid', 'Solid Line'), ('dashed', 'Dashed Line'), ('dotted', 'Dotted Line')]}), 71: ('wagtail.blocks.StructBlock', [[('style', 70)]], {}), 72: ('wagtail.blocks.TextBlock', (), {'required': False}), 73: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('light-blue', 'Light Blue'), ('dark-blue', 'Dark Blue'), ('white', 'White')]}), 74: ('wagtail.blocks.StructBlock', [[('heading', 39), ('subheading', 72), ('background_color', 73)]], {})}),
        ),
        migrations.AlterField(
            model_name='sitemenusettings',
            name='main_menu',
            field=models.ForeignKey(blank=True, help_text='Select the menu to display in the navigation bar (Legacy - will be deprecated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.mainmenu'),
        ),
        migrations.CreateModel(
            name='TopNavSubMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(help_text='Submenu item title', max_length=100)),
                ('link_url', models.URLField(blank=True, help_text='Or link to an external URL')),
                ('open_in_new_tab', models.BooleanField(default=False, help_text='Open link in new tab')),
                ('link_page', models.ForeignKey(blank=True, help_text='Link to a page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('parent', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_nav_submenu_items', to='home.topnavmenuitem')),
            ],
            options={
                'verbose_name': 'Top Nav Dropdown Item',
                'verbose_name_plural': 'Top Nav Dropdown Items',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='MiddleNavMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(help_text='Menu item title', max_length=100)),
                ('link_url', models.URLField(blank=True, help_text='Or link to an external URL')),
                ('open_in_new_tab', models.BooleanField(default=False, help_text='Open link in new tab')),
                ('link_page', models.ForeignKey(blank=True, help_text='Link to a page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('menu', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='middle_nav_items', to='home.middlenavmenu')),
            ],
            options={
                'verbose_name': 'Middle Nav Item',
                'verbose_name_plural': 'Middle Nav Items',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='BottomNavSubMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(help_text='Submenu item title', max_length=100)),
                ('link_url', models.URLField(blank=True, help_text='Or link to an external URL')),
                ('open_in_new_tab', models.BooleanField(default=False, help_text='Open link in new tab')),
                ('link_page', models.ForeignKey(blank=True, help_text='Link to a page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('parent', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_nav_submenu_items', to='home.bottomnavmenuitem')),
            ],
            options={
                'verbose_name': 'Bottom Nav Dropdown Item',
                'verbose_name_plural': 'Bottom Nav Dropdown Items',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='sitemenusettings',
            name='bottom_nav_menu',
            field=models.ForeignKey(blank=True, help_text='Select the bottom navigation bar menu (for ISO standards)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.bottomnavmenu'),
        ),
        migrations.AddField(
            model_name='sitemenusettings',
            name='middle_nav_menu',
            field=models.ForeignKey(blank=True, help_text='Select the middle navigation bar menu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.middlenavmenu'),
        ),
        migrations.AddField(
            model_name='sitemenusettings',
            name='top_nav_menu',
            field=models.ForeignKey(blank=True, help_text='Select the top navigation bar menu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.topnavmenu'),
        ),
    ]
