# Generated by Django 4.2.26 on 2025-11-14 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_bottomnavmenu_bottomnavmenuitem_middlenavmenu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemenusettings',
            name='bottom_nav_menu',
            field=models.ForeignKey(blank=True, help_text='[UNUSED] Alternative bottom nav - Main Menu is used instead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.bottomnavmenu'),
        ),
        migrations.AlterField(
            model_name='sitemenusettings',
            name='main_menu',
            field=models.ForeignKey(blank=True, help_text='Select the menu to display in the BOTTOM navigation bar (ISO Standards with dropdowns)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.mainmenu'),
        ),
        migrations.AlterField(
            model_name='sitemenusettings',
            name='middle_nav_menu',
            field=models.ForeignKey(blank=True, help_text='Select the middle navigation bar menu (ISO Certification, ISO Consultancy, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.middlenavmenu'),
        ),
        migrations.AlterField(
            model_name='sitemenusettings',
            name='top_nav_menu',
            field=models.ForeignKey(blank=True, help_text='Select the top navigation bar menu (Why Choose Us, Resources, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.topnavmenu'),
        ),
    ]
