# Generated by Django 4.2.26 on 2025-11-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_sitemenusettings_bottom_nav_menu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorthemesettings',
            name='bottom_nav_background',
            field=models.CharField(blank=True, default='#f8f9fa', help_text='Bottom navbar background color (ISO Standards)', max_length=7),
        ),
        migrations.AddField(
            model_name='colorthemesettings',
            name='bottom_nav_hover_color',
            field=models.CharField(blank=True, default='#0066cc', help_text='Bottom navbar link hover color', max_length=7),
        ),
        migrations.AddField(
            model_name='colorthemesettings',
            name='bottom_nav_text_color',
            field=models.CharField(blank=True, default='#333333', help_text='Bottom navbar text color', max_length=7),
        ),
        migrations.AddField(
            model_name='colorthemesettings',
            name='middle_nav_background',
            field=models.CharField(blank=True, default='#ffffff', help_text='Middle navbar background color (Logo, ISO Certification, etc.)', max_length=7),
        ),
        migrations.AddField(
            model_name='colorthemesettings',
            name='middle_nav_hover_color',
            field=models.CharField(blank=True, default='#0066cc', help_text='Middle navbar link hover color', max_length=7),
        ),
        migrations.AddField(
            model_name='colorthemesettings',
            name='middle_nav_text_color',
            field=models.CharField(blank=True, default='#333333', help_text='Middle navbar text color', max_length=7),
        ),
        migrations.AddField(
            model_name='colorthemesettings',
            name='top_nav_background',
            field=models.CharField(blank=True, default='#f5f5f5', help_text='Top navbar background color (Why Choose Us, Resources, etc.)', max_length=7),
        ),
        migrations.AddField(
            model_name='colorthemesettings',
            name='top_nav_hover_color',
            field=models.CharField(blank=True, default='#0066cc', help_text='Top navbar link hover color', max_length=7),
        ),
        migrations.AddField(
            model_name='colorthemesettings',
            name='top_nav_text_color',
            field=models.CharField(blank=True, default='#333333', help_text='Top navbar text color', max_length=7),
        ),
        migrations.AlterField(
            model_name='colorthemesettings',
            name='navbar_active_color',
            field=models.CharField(default='#0066cc', help_text='Default active navbar link color (fallback for all navbars)', max_length=7),
        ),
        migrations.AlterField(
            model_name='colorthemesettings',
            name='navbar_background',
            field=models.CharField(default='#ffffff', help_text='Default navbar background color (fallback for all navbars)', max_length=7),
        ),
        migrations.AlterField(
            model_name='colorthemesettings',
            name='navbar_hover_color',
            field=models.CharField(default='#0066cc', help_text='Default navbar link hover color (fallback for all navbars)', max_length=7),
        ),
        migrations.AlterField(
            model_name='colorthemesettings',
            name='navbar_text_color',
            field=models.CharField(default='#333333', help_text='Default navbar text color (fallback for all navbars)', max_length=7),
        ),
    ]
