# Generated by Django 4.2.26 on 2025-12-21 06:08

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('home', '0013_alter_homepage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Menu title (for admin reference only)', max_length=100)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number to display in top bar', max_length=30)),
                ('show_price_badge', models.BooleanField(default=False, help_text='Show price badge in top bar')),
                ('price_badge_text', models.CharField(blank=True, default='£0.00', help_text='Price badge text', max_length=30)),
                ('show_quote_button', models.BooleanField(default=True, help_text="Show 'Request a Quote' button")),
                ('quote_button_text', models.CharField(default='Request a Quote', help_text='Quote button text', max_length=50)),
                ('quote_button_link', models.URLField(blank=True, default='/contact/', help_text='Quote button link')),
                ('show_portal_button', models.BooleanField(default=True, help_text="Show 'Client Portal' button")),
                ('portal_button_text', models.CharField(default='Client Portal', help_text='Portal button text', max_length=50)),
                ('portal_button_link', models.URLField(blank=True, default='/admin/', help_text='Portal button link')),
            ],
            options={
                'verbose_name': 'Header Menu',
                'verbose_name_plural': 'Header Menus',
            },
        ),
        migrations.AddField(
            model_name='sitemenusettings',
            name='footer_menu',
            field=models.ForeignKey(blank=True, help_text='Select the footer menu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.footermenu'),
        ),
        migrations.AlterField(
            model_name='sitemenusettings',
            name='bottom_nav_menu',
            field=models.ForeignKey(blank=True, help_text='[DEPRECATED] Use Header Menu instead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.bottomnavmenu'),
        ),
        migrations.AlterField(
            model_name='sitemenusettings',
            name='main_menu',
            field=models.ForeignKey(blank=True, help_text='[DEPRECATED] Use Header Menu instead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.mainmenu'),
        ),
        migrations.AlterField(
            model_name='sitemenusettings',
            name='middle_nav_menu',
            field=models.ForeignKey(blank=True, help_text='[DEPRECATED] Use Header Menu instead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.middlenavmenu'),
        ),
        migrations.AlterField(
            model_name='sitemenusettings',
            name='top_nav_menu',
            field=models.ForeignKey(blank=True, help_text='[DEPRECATED] Use Header Menu instead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.topnavmenu'),
        ),
        migrations.CreateModel(
            name='HeaderTopLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=100)),
                ('link_url', models.URLField(blank=True)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('menu', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_links', to='home.headermenu')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HeaderMainLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=100)),
                ('link_url', models.URLField(blank=True)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('menu', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_links', to='home.headermenu')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HeaderISOStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(help_text="e.g., 'ISO 9001'", max_length=100)),
                ('link_url', models.URLField(blank=True)),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('menu', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='iso_standards', to='home.headermenu')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HeaderISODropdownItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=100)),
                ('link_url', models.URLField(blank=True)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('parent', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropdown_items', to='home.headerisostandard')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='sitemenusettings',
            name='header_menu',
            field=models.ForeignKey(blank=True, help_text='Select the header menu (includes top bar, main nav, and ISO standards)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.headermenu'),
        ),
    ]
