# Generated by Django 4.2.26 on 2026-01-10 18:14

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('home', '0017_alter_flexiblepage_body_alter_homepage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderMainLinkDropdownItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=100)),
                ('link_url', models.URLField(blank=True)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('parent', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropdown_items', to='home.headermainlink')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
