# Generated by Django 4.2.26 on 2026-01-24 11:59

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('home', '0018_headermainlinkdropdownitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Introduction text for the articles page')),
                ('show_hero', models.BooleanField(default=True, help_text='Show hero section at the top')),
                ('hero_title', models.CharField(default='ISO Resources & Expert Insights', help_text='Hero section title', max_length=255)),
                ('hero_subtitle', models.TextField(blank=True, default='Stay informed with our latest insights, expert opinions, and guidance on ISO standards and quality management.', help_text='Hero section subtitle')),
                ('show_cta', models.BooleanField(default=True, help_text='Show call-to-action section at the bottom')),
                ('cta_title', models.CharField(default='Need Personalized Guidance?', help_text='CTA section title', max_length=255)),
                ('cta_text', models.TextField(blank=True, default='Our expert team is here to help. Get in touch for a free consultation.', help_text='CTA section text')),
                ('cta_button_text', models.CharField(default='Contact Us', help_text='CTA button text', max_length=50)),
                ('cta_button_link', models.URLField(default='/contact/', help_text='CTA button link')),
            ],
            options={
                'verbose_name': 'Article Index Page',
                'verbose_name_plural': 'Article Index Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(default=django.db.models.functions.datetime.Now, help_text='Publication date of the article', verbose_name='Published date')),
                ('intro', models.TextField(help_text='Brief summary of the article (max 500 characters)', max_length=500, verbose_name='Introduction/Summary')),
                ('body', wagtail.fields.RichTextField(help_text='Main article content')),
                ('author', models.CharField(blank=True, default='Qualitation Team', help_text='Article author name', max_length=100)),
                ('card_gradient_start', models.CharField(default='#667eea', help_text='Starting color for article card gradient (hex color)', max_length=7)),
                ('card_gradient_end', models.CharField(default='#764ba2', help_text='Ending color for article card gradient (hex color)', max_length=7)),
                ('featured_image', models.ForeignKey(blank=True, help_text='Featured image for the article', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-date'],
            },
            bases=('wagtailcore.page',),
        ),
    ]
