# Generated by Django 4.2.26 on 2026-01-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_articleindexpage_articlepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleindexpage',
            name='cta_button_link',
            field=models.CharField(default='/contact/', help_text='CTA button link (can be relative path like /contact/ or full URL)', max_length=255),
        ),
    ]
