# Generated by Django 4.2.26 on 2026-01-31 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('home', '0020_alter_articleindexpage_cta_button_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_backend', models.CharField(default='django.core.mail.backends.smtp.EmailBackend', help_text='Email backend to use (usually SMTP)', max_length=255)),
                ('smtp_host', models.CharField(default='smtp.mail.yahoo.com', help_text='SMTP server address (e.g., smtp.mail.yahoo.com, smtp.gmail.com)', max_length=255, verbose_name='SMTP Host')),
                ('smtp_port', models.IntegerField(default=587, help_text='SMTP port (587 for TLS, 465 for SSL)', verbose_name='SMTP Port')),
                ('use_tls', models.BooleanField(default=True, help_text='Enable TLS encryption (recommended for port 587)', verbose_name='Use TLS')),
                ('use_ssl', models.BooleanField(default=False, help_text='Enable SSL encryption (recommended for port 465)', verbose_name='Use SSL')),
                ('smtp_username', models.CharField(blank=True, help_text='Your email address (e.g., yourname@yourdomain.com)', max_length=255, verbose_name='SMTP Username / Email')),
                ('smtp_password', models.CharField(blank=True, help_text='For Yahoo: Use app-specific password. For Gmail: Use app password', max_length=255, verbose_name='SMTP Password / App Password')),
                ('from_email', models.EmailField(blank=True, help_text='Email address that appears as sender', max_length=254, verbose_name='From Email')),
                ('contact_form_recipient', models.EmailField(blank=True, help_text='Email address where contact form submissions will be sent', max_length=254, verbose_name='Contact Form Recipient')),
                ('send_confirmation_email', models.BooleanField(default=True, help_text='Send a thank you email to form submitters', verbose_name='Send Confirmation to User')),
                ('test_email', models.EmailField(blank=True, help_text='Send a test email to this address to verify settings', max_length=254, verbose_name='Test Email Address')),
                ('is_configured', models.BooleanField(default=False, editable=False, help_text='Automatically set when all required fields are filled')),
                ('last_test_date', models.DateTimeField(blank=True, editable=False, help_text='Date when test email was last sent', null=True, verbose_name='Last Tested')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Email Settings',
            },
        ),
    ]
